package com.infor.m3.xtendm3.maven.plugin.model.type;

public enum ErrorCode {
  FILE_EXTENSION_LOOKUP_ERROR(ErrorCategory.FILE_SYSTEM),
  FILE_METADATA_NOT_FOUND_ERROR(ErrorCategory.FILE_SYSTEM),

  METADATA_PARSE_ERROR(ErrorCategory.METADATA),
  METADATA_MISSING(ErrorCategory.METADATA),
  METADATA_TRIGGER_MISSING(ErrorCategory.METADATA),
  METADATA_TRIGGER_CONFLICT(ErrorCategory.METADATA),
  METADATA_TRIGGER_PROPERTY_MISSING(ErrorCategory.METADATA),
  METADATA_INVALID_PROPERTY_FOR_EXTENSION_TYPE(ErrorCategory.METADATA),
  METADATA_INVALID_PROPERTY_FOR_TRIGGER_TYPE(ErrorCategory.METADATA),
  METADATA_INVALID_PROPERTY_FOR_PROGRAM_TYPE(ErrorCategory.METADATA),
  METADATA_INVALID_PROPERTY_FOR_METHOD_TRIGGER(ErrorCategory.METADATA),
  METADATA_INVALID_PROPERTY_FOR_TRANSACTION_TRIGGER(ErrorCategory.METADATA),

  CODE_PARSE_ERROR(ErrorCategory.EXTENSION_CODE),
  CODE_UNHANDLED_EXTENSION_TYPE_ERROR(ErrorCategory.EXTENSION_CODE),
  CODE_FORBIDDEN_PACKAGE(ErrorCategory.EXTENSION_CODE),
  CODE_FORBIDDEN_IMPORT(ErrorCategory.EXTENSION_CODE),
  CODE_FORBIDDEN_INTERFACE(ErrorCategory.EXTENSION_CODE),
  CODE_FORBIDDEN_SUPERTYPE(ErrorCategory.EXTENSION_CODE),
  CODE_FORBIDDEN_INJECTION_ERROR(ErrorCategory.EXTENSION_CODE),
  CODE_FORBIDDEN_DECLARATION_ERROR(ErrorCategory.EXTENSION_CODE),
  CODE_MISSING_MAIN_METHOD_ERROR(ErrorCategory.EXTENSION_CODE),

  INTERNAL_ERROR(ErrorCategory.INTERNAL);

  private final ErrorCategory category;

  ErrorCode(ErrorCategory category) {
    this.category = category;
  }

  public ErrorCategory getCategory() {
    return category;
  }
}
